### ISSUE TITLE
Use instance template with ops-agent

### ISSUE THREAD

**Issue by dchaley** [dchaley/deepcell-segmentation#348]
If we create an instance template with the ops-agent installed, then we'll get memory metrics.
These are disabled by default due to resource usage of the monitoring agent.

1) create template w/ ops-agent installed
2) change job submission to use template

**Comment by dchaley-mayo** [comment]
We can actually do this with a flag now, let's do that instead: https://cloud.google.com/batch/docs/create-run-job-ops-agent

```json
  "allocationPolicy": {
    "instances": [
      {
        "installOpsAgent": true
      }
    ]
  },
```

Note required permissions here: [docs](https://cloud.google.com/batch/docs/create-run-job-ops-agent#ops-agent-requirements)

> * [Monitoring Metric Writer ](https://cloud.google.com/iam/docs/understanding-roles#monitoring.metricWriter)(roles/monitoring.metricWriter) on the project
> * [Logs Writer ](https://cloud.google.com/iam/docs/understanding-roles#logging.logWriter)(roles/logging.logWriter) on the project

**Comment by dchaley** [comment]
cc @lynnlangit  we'll need to make sure the service account in the target environment has those permissions ^^    if not, we won't be able to monitor memory easily (we can still add strategic print statements, it's not so bad).
